### PR TITLE
feat: add `alejandra` formatter for `nix`

### PR DESCRIPTION
**Pull request by marcelarie**
Alternative to `nixpkgs-fmt` and `nixfmt`.

### CODE REVIEW

**Comment by sbc64** [comment]
This is working for me so far.

**Comment by marcelarie** [comment]
I just realized that the `--quiet` flags is faster. Should I add it? 

This is the results running in the same repo:
without `--quiet`: 255.27 millis
with `--quiet`: 6.25 millis

**Comment by marcelarie** [comment]
hmm now with it fails with the arguments. I don't understand why, I tested it on my local config and the formatting works.

**Comment by marcelarie** [comment]
Ok it fails to load the built-in, I rolled back to the past commit.

**Comment by marcelarie** [comment]
I rolled back the commit and it failed too. 🤷🏽‍♂️

**Comment by jose-elias-alvarez** [comment]
Are you talking about CI or the formatter itself? The CI failure is unrelated and I just pushed a fix, so let me know if this is good to go otherwise.

**Comment by marcelarie** [comment]
Good to go @jose-elias-alvarez !

**Comment by jose-elias-alvarez** [comment]
Excellent, thank you!

**Pull request merged**
