### PR TITLE
Add ruleId to eslint adapter

### PR DESCRIPTION
**Pull request by benwainwright**
Without the ruleid in the diagnostic, this plugin is quite hard to use with eslint...

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
I don't think this should be a default, as it's inconsistent with other sources. You can already change the format of diagnostic messages from a specific linter using [the method described in the documentation](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#eslint).

**Comment by benwainwright** [comment]
@jose-elias-alvarez if its inconsistent with other sources then they should be changed to. This is a massive omission and serious usability issue - its pretty much unusable without it because most people respond to a linter error by googling the rule id if its in any way confusing (which is a lot)

**Comment by benwainwright** [comment]
@jose-elias-alvarez are you serious? This plugin is completely unusable for eslint without this. If you even slightly use a linter you will find yourself googling rules based on the rule id _all the time_. If its inconsistent with other sources then the other sources should be changed...

**Comment by benwainwright** [comment]
@jose-elias-alvarez please reconsider. I don't see anything in the documentation you linked to which would provide the behaviour I'm after

**Comment by benwainwright** [comment]
What I'm proposing is pretty standard. E.g. https://github.com/creativenull/diagnosticls-configs-nvim/blob/eed632a079064bdf415f1f9e128998da3b61bff0/lua/diagnosticls-configs/linters/eslint.lua#L14 (I really don't want to use `diagnosticls` though)

**Comment by jose-elias-alvarez** [comment]
Apologies, I pasted the wrong link. [Here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#diagnostics-format) is the relevant page.

**Pull request closed without merging**
