### PR TITLE
remove exit code checking from sqlfluff

### PR DESCRIPTION
**Pull request by WhoIsSethDaniel**
I never get diagnostic information unless I remove the `check_exit_code` from the `sqlfluff` configuration.

### CODE REVIEW

**Comment by syphar** [comment]
This is odd, I can reproduce the issue, but I'm not sure this is the correct solution, perhaps @jose-elias-alvarez could provide insight? 

I understood `check_exit_code` that it should `return true` when null-ls should read the diagnostics. 

Also comparing to other builtins like `gitlint` this seems to work, 

except in this case here. With `sqlfluff` it seems like the diagnostics are only read when we `return false` in `check_exit_code`.

**Comment by WhoIsSethDaniel** [comment]
@syphar I also was uncertain if this was the correct solution. It seemed strange at the time, but worked. :-/

**Comment by syphar** [comment]
@WhoIsSethDaniel I think #1058 is the better solution

**Comment by WhoIsSethDaniel** [comment]
As long is it works!

**Pull request closed without merging**
