### PR TITLE
feat(builtins): Add rpmspec diagnostics builtin

### PR DESCRIPTION
**Pull request by cryptomilk**
This add diagnostics for RPM spec files.

rpmspec

### CODE REVIEW

**Comment by cryptomilk** [comment]
Maybe we will get --stdin support https://github.com/rpm-software-management/rpm/issues/1926

**Comment by jose-elias-alvarez** [comment]
Excellent, let's hope this gets stdin support, but this looks good for now. Could you just add an entry to the documentation?

**Comment by cryptomilk** [comment]
I've added the requested entry.

**Comment by jose-elias-alvarez** [comment]
Thanks!

**Pull request merged**
