### PR TITLE
feat(builtin): Add `textlint` diagnostic

### PR DESCRIPTION
**Pull request by yuys13**
Hi, thanks for the great software!
I tried to add textlint to null-ls, as I often use textlint when writing.
I'm afraid I wrote the same function in several places, but I couldn't think of a better way. Since the diagnostics are compatible with eslint, I wrote the same function as eslint.
Please review.

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Thanks! If you wait until I've had a chance to review and merge #521, we might be able to combine this with ESLint (though it might still be best to keep them separated – I want to think about it a bit more).

**Comment by jose-elias-alvarez** [comment]
We could theoretically merge it with this diff:

```diff
--- Result of linting is compatible for eslint
-local handle_eslint_output = function(params)
-    params.messages = params.output and params.output[1] and params.output[1].messages or {}
-    if params.err then
-        table.insert(params.messages, { message = params.err })
-    end
-
-    local parser = h.diagnostics.from_json({
-        attributes = {
-            severity = "severity",
-        },
-        severities = {
-            h.diagnostics.severities["warning"],
-            h.diagnostics.severities["error"],
-        },
-    })
-
-    return parser({ output = params.messages })
-end
-
 return h.make_builtin({
     name = "textlint",
     method = DIAGNOSTICS,
@@ -33,7 +13,7 @@ return h.make_builtin({
         args = { "-f", "json", "--stdin", "--stdin-filename", "$FILENAME" },
         format = "json_raw",
         check_exit_code = { 0, 1 },
-        on_output = handle_eslint_output,
+        on_output = require("null-ls").builtins.diagnostics.eslint._opts.on_output,
     },
     factory = h.generator_factory,
 })
```

I don't feel strongly about this, but if I had to choose, I'd say I prefer keeping it separate to make sure that future changes on one end don't break the other end. In that case, we could rename the local `handle_eslint_output` helper to `handle_output` and this would be ready to merge.

**Comment by yuys13** [comment]
Thanks for reviewing!

> We could theoretically merge it with this diff:

I also understand that I can use `on_output` around in this case.

>  I'd say I prefer keeping it separate to make sure that future changes on one end don't break the other end. 

Agreed.

> In that case, we could rename the local handle_eslint_output helper to handle_output and this would be ready to merge.

I fixed it!

**Comment by jose-elias-alvarez** [comment]
Thank you!

**Pull request merged**
