### PR TITLE
Add support formatting for `fennel` lang

### PR DESCRIPTION
**Pull request by babygau**
It will format `*.fnl` file using [`fnlfmt`](https://git.sr.ht/~technomancy/fnlfmt)

### CODE REVIEW

**Comment by vuki656** [comment]
It would be nice if you could also update the docs [here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md).

**Comment by jose-elias-alvarez** [comment]
Thanks for this! And yep, I'd appreciate it if you could add a section to the documentation so other users are able to know we've added support.

**Comment by babygau** [comment]
> Thanks for this! And yep, I'd appreciate it if you could add a section to the documentation so other users are able to know we've added support. (Edit: also a good reminder that we should probably put together a quick contribution guide.) 

Sure, I'll update the doc later on tonight 😀👍

**Comment by babygau** [comment]
@jose-elias-alvarez, I updated the docs as your suggestion. Thank you!

**Comment by jose-elias-alvarez** [comment]
Thank you!

**Pull request merged**
