### PR TITLE
fix(diagnostics): parse all file for todo-comments

### PR DESCRIPTION
**Pull request by danilshvalov**
Refers to #1085

### CODE REVIEW

**Review by jose-elias-alvarez — APPROVED** [review]
LGTM, and this fixes the example from the original issue. Let's wait for feedback from the original reporter.

**Comment by heygarrett** [comment]
This fixes the issue for Lua, but I'm still not seeing any diagnostics for other languages (I tried TypeScript and Python). Could I be holding it wrong?

**Comment by danilshvalov** [comment]
Have you installed treesitter parser for these languages?

**Comment by heygarrett** [comment]
Yeah, I even tried uninstalling and reinstalling the TypeScript parser. No luck. Any other information I can provide?

Also should I be leaving these comments on the issue rather than the PR?

**Comment by jose-elias-alvarez** [comment]
For TypeScript, it looks like the node's type is `comment`. I am not a Treesitter expert, but does this diff make sense? It seems to make things work on my end:

```diff
diff --git a/lua/null-ls/builtins/diagnostics/todo_comments.lua b/lua/null-ls/builtins/diagnostics/todo_comments.lua
index cfa747f..82682bd 100644
--- a/lua/null-ls/builtins/diagnostics/todo_comments.lua
+++ b/lua/null-ls/builtins/diagnostics/todo_comments.lua
@@ -4,6 +4,8 @@ local methods = require("null-ls.methods")
 local DIAGNOSTICS = methods.internal.DIAGNOSTICS
 local SEVERITIES = h.diagnostics.severities
 
+local comment_types = { "comment", "comment_content" }
+
 local function get_document_root(bufnr)
     local has_parser, parser = pcall(vim.treesitter.get_parser, bufnr)
     if not has_parser then
@@ -20,7 +22,7 @@ end
 
 local function parse_comments(root, output)
     for node in root:iter_children() do
-        if node:type() == "comment_content" then
+        if vim.tbl_contains(comment_types, node:type()) then
             table.insert(output, node)
         else
             parse_comments(node, output)
```

**Comment by heygarrett** [comment]
@jose-elias-alvarez Yup, that works for me as well!

**Comment by heygarrett** [comment]
Maybe unrelated, but the diagnostic is applied to the whole line (including preceding whitespace) rather than just the comment content. Is that expected?

**Comment by danilshvalov** [comment]
Are you talking about a message after the TODO keyword?

**Comment by heygarrett** [comment]
Screen Shot 2022-09-09 at 16 18 01

My diagnostics use underlines, and the whole line is getting underlined. I suppose I'd only expect the keyword itself (in this screenshot `TODO`) to get underlined (or maybe the keyword and the text that follows it).

**Comment by danilshvalov** [comment]
Can you try the latest patch?

**Comment by heygarrett** [comment]
That's great! Thanks for the quick fix. I'd say this is ready to merge. 👍

**Comment by jose-elias-alvarez** [comment]
Excellent, thank you @danilshvalov for the improvements!

**Pull request merged**
