### PR TITLE
Fix markdownlint_cli2 built-in

### LINKED ISSUE #1256: markdownlint_cli2 not working with builtin
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.8.1

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Arch Linux

### Minimal Config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {null_ls.builtins.diagnostics.markdownlint_cli2},
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to Reproduce

Use the above built in config. I found when using this config, everything worked fine:

```lua
local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
       sources = { null_ls.builtins.diagnostics.markdownlint_cli2.with { args = { "$FILENAME" } } },
       debug = true,
    })
```

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

To see diagnostics in my project

### Actual Behavior

No diagnostics show in the buffer.

### Debug Log

```
[TRACE Fri 25 Nov 2022 23:04:51] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Fri 25 Nov 2022 23:04:51] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:123: received LSP request for method initialize
[DEBUG Fri 25 Nov 2022 23:04:51] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:165: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {                                                
    uri = "file:///home/d/src/dngray/pg/privacyguides.org/README.md"
  }
}
[TRACE Fri 25 Nov 2022 23:04:51] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:148: received LSP notification for method initialized
[TRACE Fri 25 Nov 2022 23:04:51] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:148: received LSP notification for method textDocument/didOpen
[TRACE Fri 25 Nov 2022 23:04:51] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Fri 25 Nov 2022 23:04:51] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:320: spawning command "markdownlint-cli2" at /home/d/src/dngray/pg/privacyguides.org with args {}
[TRACE Fri 25 Nov 2022 23:04:52] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:204: error output: markdownlint-cli2 v0.5.1 (markdownlint v0.26.2)
https://github.com/DavidAnson/markdownlint-cli2
    
Syntax: markdownlint-cli2 glob0 [glob1] [...] [globN]
        markdownlint-cli2-fix glob0 [glob1] [...] [globN]
        markdownlint-cli2-config config-file glob0 [glob1] [...] [globN]

Glob expressions (from the globby library):
- * matches any number of characters, but not /
- ? matches a single character, but not /
- ** matches any number of characters, including /
- {} allows for a comma-separated list of "or" expressions
- ! or # at the beginning of a pattern negate the match
- : at the beginning identifies a literal file path
    
Dot-only glob:
- The command "markdownlint-cli2 ." would lint every file in the current directory tree which is probably not intended
- Instead, it is mapped to "markdownlint-cli2 *.{md,markdown}" which lints all Markdown files in the current directory
- To lint every file in the current directory tree, the command "markdownlint-cli2 **" can be used instead

Configuration via:
- .markdownlint-cli2.jsonc
- .markdownlint-cli2.yaml
- .markdownlint-cli2.cjs or .markdownlint-cli2.mjs
- .markdownlint.jsonc or .markdownlint.json
- .markdownlint.yaml or .markdownlint.yml
- .markdownlint.cjs or .markdownlint.mjs
    
Cross-platform compatibility:
- UNIX and Windows shells expand globs according to different rules; quoting arguments is recommended
- Some Windows shells don't handle single-quoted (') arguments well; double-quote (") is recommended
- Shells that expand globs do not support negated patterns (!node_modules); quoting is required here
- Some UNIX shells parse exclamation (!) in double-quotes; hashtag (#) is recommended in these cases
- The path separator is forward slash (/) on all platforms; backslash (\) is automatically converted

The most compatible syntax for cross-platform support:
$ markdownlint-cli2 "**/*.md" "#node_modules"

[TRACE Fri 25 Nov 2022 23:04:52] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:205: output: nil
[TRACE Fri 25 Nov 2022 23:04:52] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:181: received diagnostics from source 1
[TRACE Fri 25 Nov 2022 23:04:52] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:182: {}
```

### Help

No

### Implementation Help

_No response_

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

### PR DESCRIPTION
**Pull request by dngray**
Fixes: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1256

It seems to work for me.

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
So the issue here is that markdownlint-cli2 is meant to lint globs, not single files (see [the documentation](https://github.com/DavidAnson/markdownlint-cli2#command-line)). The user either needs to specify a `globs` property in their config file or add an argument in their null-ls config that specifies a glob to be linted, e.g. `args = { "**/*.md" }`. Can we update the documentation accordingly?

**Comment by dngray** [comment]
Sure, I didn't have a lot of experience with this.

Would you like me to open an issue upstream?

**Comment by jose-elias-alvarez** [comment]
I think it's working as expected, so I just mean in terms of updating our documentation here. If you look at the built-in's source, you'll see that we have a field where we can inject Markdown that will then be output into [this file](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md). We can then tell users about the specific configuration requirements for this source.

**Comment by dngray** [comment]
So are you saying:

```
local null_ls = require('null-ls')
null_ls.setup {
  sources = {
    null_ls.builtins.diagnostics.markdownlint_cli2.with {
      args = { "**/*.md" },
    },
  },
}
```

Is actually correct?

**Comment by jose-elias-alvarez** [comment]
You could do that, or you could use `globs` a config file (which I imagine would be the preferred approach on non-solo projects). You can see [this document](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/CONTRIBUTING.md) for info on adding to the documentation.

**Pull request closed without merging**
