### PR TITLE
feat(ruff): add support for ruff python linter

### PR DESCRIPTION
**Pull request by vsedov**

### CODE REVIEW

**Comment by vsedov** [comment]
Quick note: I wasn't sure how to deal with severity, and currently only works when you have a project.toml, I il try working around this.

**Comment by jose-elias-alvarez** [comment]
Exit code handling looks good! I poked around the repository and wasn't able to find any information about `stdin` support, so I think using a temp file will provide the best experience (though it may run into issues resolving config files until #1075 is merged).

**Comment by vsedov** [comment]
Is there a good example for using a temp file ?  Im guessing something like [this](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/pydocstyle.lua) Right  ?
Il try messing around with temp files a bit more. 

Cheers.

**Comment by jose-elias-alvarez** [comment]
Right, setting `to_temp_file = true` should make it work with no additional code. I merged #1075, so I think everything should work as expected, but let me know.

**Comment by vsedov** [comment]
That should be it, didn't come across any major errors only thing that confused me was in poetry projects it required the root dir, but as you stated, pretty certain that can be updated in the docs.

**Comment by jose-elias-alvarez** [comment]
Great, this looks good to go! If we can just add a mention of any setup requirements to the `notes` field, I think this is ready to merge (more info [here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/CONTRIBUTING.md#contributing-built-ins)).

**Comment by YangtseSu** [comment]
1. [Support linting input from stdin](https://github.com/charliermarsh/ruff/commit/8ba872ece460a760e7bac4949759d12feb917f35)
We can use `--stdin-filename` now.
2.ruff raise an error when `No pyproject.toml found`, null-ls did not pass the error message to on_output in this case.
```
ruff ./E402.py
No pyproject.toml found.
Falling back to default configuration...
Found 11 error(s).
E402.py:6:1: F401 `a` imported but unused
E402.py:9:5: F401 `b` imported but unused
E402.py:15:1: F401 `c` imported but unused
E402.py:17:4: F821 Undefined name `x`
E402.py:18:5: F401 `d` imported but unused
E402.py:20:5: F401 `e` imported but unused
E402.py:22:5: F821 Undefined name `x`
E402.py:24:1: E402 Module level import not at top of file
E402.py:24:1: F401 `f` imported but unused
E402.py:28:5: F401 `e` imported but unused
E402.py:32:5: F401 `g` imported but unused
8 potentially fixable with the --fix option.ruff ./E402.py
No pyproject.toml found.
Falling back to default configuration...
Found 11 error(s).
E402.py:6:1: F401 `a` imported but unused
E402.py:9:5: F401 `b` imported but unused
E402.py:15:1: F401 `c` imported but unused
E402.py:17:4: F821 Undefined name `x`
E402.py:18:5: F401 `d` imported but unused
E402.py:20:5: F401 `e` imported but unused
E402.py:22:5: F821 Undefined name `x`
E402.py:24:1: E402 Module level import not at top of file
E402.py:24:1: F401 `f` imported but unused
E402.py:28:5: F401 `e` imported but unused
E402.py:32:5: F401 `g` imported but unused
8 potentially fixable with the --fix option.
```

**Comment by YangtseSu** [comment]
I tried to fix this.
This file works under all the conditions I have tested.
[ruff.lua](https://gist.github.com/YangtseSu/e7dec74d4ab83e640cec69073eca4f99)

**Comment by vsedov** [comment]
> I tried to fix this. This file works under all the conditions I have tested. But I don't know how to submit a commit to this PR. [ruff.lua](https://gist.github.com/YangtseSu/e7dec74d4ab83e640cec69073eca4f99)

Hi il add it now, I'm very sorry I have not been working on this, I've been focusing on uni so my time has become very niche, it should be up now :)

**Comment by vsedov** [comment]
Think this is good to merge?  @jose-elias-alvarez Did we miss anything?

**Comment by haoyun** [comment]
> Think this is good to merge? @jose-elias-alvarez Did we miss anything?

I would like to see this to be merged. However, as mention above,

> If we can just add a mention of any setup requirements to the notes field, I think this is ready to merge

**Comment by YangtseSu** [comment]
> > Think this is good to merge? @jose-elias-alvarez Did we miss anything?
> 
> I would like to see this to be merged. However, as mention above,
> 
> > If we can just add a mention of any setup requirements to the notes field, I think this is ready to merge

Install ruff and enable ruff diagnostics. Nothing special needs to be added to "notes" currently.

**Comment by jose-elias-alvarez** [comment]
> > > Think this is good to merge? @jose-elias-alvarez Did we miss anything?
> > 
> > 
> > I would like to see this to be merged. However, as mention above,
> > > If we can just add a mention of any setup requirements to the notes field, I think this is ready to merge
> 
> Install ruff and enable ruff diagnostics. Nothing special needs to be added to "notes" currently.

My understanding was that this source only works if you have a project.toml file. If that's the case, this should be mentioned in the documentation. Ideally we could also catch errors stemming from missing config files and show them as diagnostics, as in [this example](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/1ac465b1617b28f753cb875d8ac1d0f23c0b96d4/lua/null-ls/builtins/diagnostics/pmd.lua#L4), but we can save that for a follow-up.

If that's not the case and the linter runs properly without any additional setup, then this is good to go, so let me know.

**Comment by YangtseSu** [comment]
The linter runs properly without any additional setup, now.

**Comment by YangtseSu** [comment]
There are two things that may need to be resolved in the future. One is that the upstream does not distinguish between errors, warnings and information, but outputs error information according to the function. The severity is not absolutely correct.ruff is in very active development, and new error types may appear.

The second is that ruff has the - fix option, maybe it is possible to add code_actions.

**Comment by jose-elias-alvarez** [comment]
Great, thanks for confirming and thanks everyone for the work on this!

**Pull request merged**
