### PR TITLE
Add a builtin for using `gccdiag`

### PR DESCRIPTION
**Pull request by IndianBoy42**
Get diagnostics from gcc with the correct compiler arguments

Requires a `compiler_commands.json` file at the root of the working directory.

### CODE REVIEW

**Comment by IndianBoy42** [comment]
Addresses #148

**Comment by jose-elias-alvarez** [comment]
This looks good to me, do you think it's ready to merge? You mentioned in #148 that you wanted to get arguments from a JSON file. I don't know about the complexity involved, but it should theoretically be possible by setting `args` to a function that parses the file and returns the arguments (ideally caching them somehow to prevent parsing on each run).

**Comment by IndianBoy42** [comment]
So now gccdiag handles parsing the compile_commands.json (usually generated by cmake) and invokes the compiler with the correct arguments. We don't have to do that ourselves

Oh you know what I forgot to link it properly in the PR description. 

https://gitlab.com/andrejr/gccdiag

I'm not invoking GCC directly as you see, gccdiag is basically a wrapper that looks through compile_commands and invokes gcc with the correct arguments

It's not perfect but very useful

**Comment by jose-elias-alvarez** [comment]
Okay, got it. Do you think it might be a good idea to add a description of gccdiag to the documentation, too, in case users are unfamiliar with it?

**Comment by IndianBoy42** [comment]
Yeah that makes sense, I'll do that, in a few hours

**Comment by jose-elias-alvarez** [comment]
Great, thanks!

**Pull request merged**
