### PR TITLE
fix(builtins): cspell parse multiline jsons

### PR DESCRIPTION
**Pull request by marianozunino**
My `lua` skills are as good as my tailoring...

Thanks to @peterfication for this comment: 
https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1154#issuecomment-1362590225

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Thanks! While we're fixing this, could we also fix [this check](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/158d5817da817c81123d24c2c392e0f517ed532b/lua/null-ls/builtins/code_actions/cspell.lua#L92)? We should check if `cspell_json_file == nil` and not an empty string. I also think it's more appropriate as a warning.

**Comment by marianozunino** [comment]
> Thanks! While we're fixing this, could we also fix [this check](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/158d5817da817c81123d24c2c392e0f517ed532b/lua/null-ls/builtins/code_actions/cspell.lua#L92)? We should check if `cspell_json_file == nil` and not an empty string. I also think it's more appropriate as a warning.

You bet.

Also I added the `create_cspell_json` function which, well, creates the file if is not present. Also, this behaviour may be prevented using the config table.

```lua
	null_ls.builtins.code_actions.cspell.with({
		config = {
			create_config_file = false, -- defaults to true
		},
	}),
```

**Comment by jose-elias-alvarez** [comment]
Pushed a couple of small changes but this looks good and seems to be working well on my end. Thanks for working on this!

**Comment by peterfication** [comment]
Thanks a lot for incorporating the quick fix :)

**Comment by PumpedSardines** [comment]
Thank you all so much! Nice to see this fix being merged!!!

**Pull request merged**
