### PR TITLE
Add mypy diagnostic builtin for Python.

### PR DESCRIPTION
**Pull request by dsully**

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Can you verify whether this updates diagnostics when the buffer's content changes (before saving the file to the disk)? #139 has some discussion about how `mypy` doesn't seem to have proper `stdin` support and may require additional work (changing the arguments or using a temp file).

**Comment by dsully** [comment]
You're right - but it looks like we can use mypy's `--shadow-file` option if `null-ls` provides access to the tempfile.

I see you already referenced https://github.com/python/mypy/issues/2119 which talks about this.

**Comment by jose-elias-alvarez** [comment]
null-ls built-ins have access to a `to_temp_file` flag, which will write a file to a temporary directory (`/tmp` on Unix). We can try that out with `--shadow-file`, though from what I understand, `mypy` needs to scan the whole directory for accurate type checking, so we'd need to make sure that the arguments make `mypy` aware of where the actual file is.

**Comment by WhyNotHugo** [comment]
`to_temp_file` seems to fall a bit short -- `mypy` needs to be passed two paths:

- The location of the _actual_ file, to resolve relative imports, etc.
- The location of the `--shadow-file`, which is, in this case, the temporary file.

However, when using `to_temp_file`, the original path is no longer available.

**Comment by jose-elias-alvarez** [comment]
I made a small change in fce6e29c589ed4e1d617d4fdd80af8e49bf5281a so that `args` functions have access to both paths:

```lua
args = function(params)
    print(params.bufname) -- original
    print(params.temp_path) -- temp path
    return { "actual", "args", "here" }
end
```

Let me know if that makes it possible to handle this, or if further changes are needed.

**Comment by nawordar** [comment]
I wanted to try to finish this feature, but I stumbled across a different problem: `mypy` exits with error code 2 when there is almost any kind of error — including invalid command arguments and syntax error.

If I make `check_exit_code` return `true` on error code 2, then some important errors can get ignored and I also get duplicated "invalid syntax" error from pyflakes (from python-language-server):

```
def convert_quantity(quantity: int) - float:     ■ invalid syntax     ■ invalid syntax
```

When I make it return `false`, then neovim spams error messages before I finish writing the code. What should I do in this situation?

**Comment by jose-elias-alvarez** [comment]
@nawordar One option might be to have `check_exit_code` always return `true`, then set `format = raw` so you can check the output, then either feed it into one of the parsers or parse it manually.

**Comment by jose-elias-alvarez** [comment]
Closed by #325.

**Pull request closed without merging**
