### PR TITLE
feat: enable project-level diagnostics for revive, staticcheck

### PR DESCRIPTION
**Pull request by xenrox**
Change to go linters as discussed.

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Great, thank you for this and for your feedback on the PR!

**Comment by fitrh** [comment]
Sorry to comment here, but did you guys know that adding `./...` to the end of the arguments makes `extra_args` for revive unusable? or is this the intention?

**Comment by fitrh** [comment]
I'm sure not, revive uses it for project/package diagnostics, but we can't pass any other arguments after that, e.g. add `-c` to read configuration from current project, as in my workflow define `revive.toml` for each project.

@xenrox did you aware of this ?

Actually this is not a problem as we can just override the `args`, but again, `extra_args` will be unusable

**Comment by xenrox** [comment]
Yes that is a problem for both revive and staticcheck that cannot easily be circumvented I think. As soon as you pass the first file (or in this case `./...`) to one of these linters, they no longer accept any configuration arguments.
@jose-elias-alvarez Do you think this particular behavior/quirk should be documented?

**Comment by jose-elias-alvarez** [comment]
I see, I can't think of a better workaround for this case than to override `args` completely. A PR documenting this quirk would be very appreciated!

**Comment by xenrox** [comment]
Have submitted a first version here: https://github.com/jose-elias-alvarez/null-ls.nvim/pull/888

**Pull request merged**
