### PR TITLE
fix(builtins): haml_lint - add to_temp_file = true and notes

### LINKED ISSUE #1144: Haml-lint: failed to decode json: Expected value but found invalid token at character 1
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.7.2

### Operating System

macOS Big Sur

### Minimal config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = { null_ls.builtins.diagnostics.haml_lint },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to reproduce

1. Write a haml file, e.g., `test.html.haml`.
  I used the following content, which should throw a linting error:
  ```haml
  %h1 This is haml
    %p yes it is.
  ```

2. Open this in neovim with the above minimal config.
3. See error.

### Expected behavior

I should see proper diagnostics (running the command `haml-lint --reporter json test.html.haml` works fine from the command line).

### Actual behavior

Received an error:
`failed to decode json: Expected value but found invalid token at character 1`

See included Debug log for more info

### Debug log

```
[TRACE Thu Sep 29 09:47:18 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Thu Sep 29 09:47:18 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:123: received LSP request for method initialize
[DEBUG Thu Sep 29 09:47:18 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:165: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///Users/ag/repos/repo/test.html.haml"
  }
}
[TRACE Thu Sep 29 09:47:18 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:148: received LSP notification for method initialized
[TRACE Thu Sep 29 09:47:18 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:148: received LSP notification for method textDocument/didOpen
[TRACE Thu Sep 29 09:47:18 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Thu Sep 29 09:47:18 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:321: spawning command "haml-lint" at /Users/ag/repos/repo with args { "--reporter", "json", "/Users/ag/repos/repo/test.html.haml" }
[TRACE Thu Sep 29 09:47:21 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:209: error output: warning: parser/current is loading parser/ruby30, which recognizes3.0.4-compliant syntax, but you are running 3.0.1.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

[TRACE Thu Sep 29 09:47:21 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:210: output: {"metadata":{"haml_lint_version":"0.37.1","ruby_engine":"ruby","ruby_patchlevel":"64","ruby_platform":"x86_64-darwin20"},"files":[{"path":"/Users/ag/repos/repo/test.html.haml","offenses":[{"severity":"error","message":"Illegal nesting: content can't be both given on the same line as %h1 and nested within it.","location":{"line":1},"linter_name":"Syntax"}]}],"summary":{"offense_count":1,"target_file_count":1,"inspected_file_count":1}}

[WARN  Thu Sep 29 09:47:21 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:92: failed to run generator: ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:64: failed to decode json: Expected value but found invalid token at character 1
```

### Help

No

### Implementation help

_No response_

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

### PR DESCRIPTION
**Pull request by adonespitogo**
Should fix #1144 

Added generator option `to_temp_file = true` and notes for `haml_lint` builtin diagnostics.

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
@aedwardg Can you check if this works for you?

**Comment by aedwardg** [comment]
@jose-elias-alvarez 

The `to_temp_file` line is 100% needed.

The notes about globally installing Rubocop, however, I think were unique to @adonespitogo's case.
Both haml-lint and Solargraph use Rubocop for some diagnostics, so rubocop is needed to run them, but both should respect project-specific installations of Rubocop installed via `bundle install`.
 

Since I've never had to install Rubocop globally to make anything work, I'd be in favor changing the note to say something like the following:
>"haml-lint interacts with other code analyzers like Rubocop. Warnings from Rubocop may break diagnostics for this plugin if they are not received in valid JSON format. Common culprits are additional Rubocop dependencies that need to be installed or parser version warnings."

In my case, what I believe is causing the problem for my work repo is the parser version warning that gets output every time rubocop or haml-lint are run.  Apparently it has been driving people crazy for years.
See these issues for example:
https://github.com/rubocop/rubocop/issues/1819
https://github.com/vim-syntastic/syntastic/issues/1418
https://github.com/whitequark/parser/issues/870

**Comment by adonespitogo** [comment]
My intention for installing them globally was to avoid having to install them for every project that I work on. But I agree that it should respect project-specific installations. I'll change the notes as you described.

**Comment by jose-elias-alvarez** [comment]
Alright, thanks all!

**Pull request merged**
