### PR TITLE
fix: Update the sqlfluff diagnostics built-in

### PR DESCRIPTION
**Pull request by KingMichaelPark**
- The sqlfluff diagnostics linter was treating 1 exit codes as passing which was incorrect.
- I have adjusted the output method to conform to the way sqlfluff outputs diagnostics to stderr.
- Made default arguments more explicit instead of shortened flag

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Thanks! This looks good to me. @Alvinferdi990 could you verify whether this fixes your issue?

**Comment by syphar** [comment]
I was just testing it (and it is still broken), then I realized one thing: 

this PR is changing the _diagnostics_ source for sqlfluff, not the _formatting_ source. So there is no way this can fix the formatting issue

**Comment by KingMichaelPark** [comment]
Okay, it must be that both were broken because the debugging behaviour was incorrect as well on postgres as an input source, hold off on merging this for now, I will check the formatter as well.

**Comment by KingMichaelPark** [comment]
@syphar could you send me an example query? It seems that I can format things with postgres without any changes to my config, it does only format if it doesn't have any diagnostic issues which I suppose makes sense

**Comment by syphar** [comment]
@KingMichaelPark I used the example query from #1123 , using the postgres dialect: https://github.com/syphar/dotfiles/blob/1a3cbb0e34e336bc3c109236056ce00065e4f475/.config/nvim/lua/dc/lsp/null_ls.lua#L124-L126

**Comment by KingMichaelPark** [comment]
Okay I couldn't get it to insert debug issues (replicating your issue) when running but I have added extra precautions to the json parser for bad output when the `--github-anotations` flag seems to append additional - non-json - output in certain situations . It might be useful to have a more experienced sqlfluff dev check why this happens. @alanmcruickshank I don't think you need to contribute necessarily unless scanning this for a few minutes would lead to something obvious that I am missing.

**Comment by syphar** [comment]
just a thought: wouldn't it be the best solution to just fix sqlfluff here?

**Comment by KingMichaelPark** [comment]
The first commit is fine regardless but the second I agree should be raised there if you don't mind.

**Comment by alanmcruickshank** [comment]
If you find examples of when sqlfluff outputs inappropriate stuff on either stdout or stderr, do post them a issues on the sqlfluff GitHub - they should be fairly easy to squash. The intent is that it should play nice with use cases like this.

**Comment by KingMichaelPark** [comment]
Will raise a ticket there with this example then, thank you @alanmcruickshank  I appreciate it.

image

**Comment by jose-elias-alvarez** [comment]
Thanks @KingMichaelPark and @alanmcruickshank, was the conclusion here to fix the behavior upstream, then?

**Comment by KingMichaelPark** [comment]
It needs more investigating, my config was disallowing me from seeing the issue but after seeing it I can confirm that the sqlfluff fix is inserting that parsing error he has reported to the file and no combination of changing the formatting options remedies it so I will have to check the sqlfluff code to see what is happening.

Michael Park
Senior Data Engineer
[The Data Shed Logo]
________________________________
From: Jose Alvarez ***@***.***>
Sent: 29 September 2022 14:40
To: jose-elias-alvarez/null-ls.nvim ***@***.***>
Cc: Michael Park ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [jose-elias-alvarez/null-ls.nvim] fix: Update the sqlfluff diagnostics built-in (PR #1137)


Thanks @KingMichaelPark<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKingMichaelPark&data=05%7C01%7Cmichaelpark%40thedatashed.co.uk%7C6600873a48fd41417baf08daa2201fd3%7Cf420563810bb4ebda523e746a01ddade%7C0%7C0%7C638000556098797552%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MTnTooGff5kP8I3soBwRoqpBSR4EgZZBiufsw2yFYzA%3D&reserved=0> and @alanmcruickshank<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falanmcruickshank&data=05%7C01%7Cmichaelpark%40thedatashed.co.uk%7C6600873a48fd41417baf08daa2201fd3%7Cf420563810bb4ebda523e746a01ddade%7C0%7C0%7C638000556098797552%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q9YDdmQ34H01cVWQglRUGrJ5qzVQz15xeFIisOpHbA4%3D&reserved=0>, was the conclusion here to fix the behavior upstream, then?

**Comment by syphar** [comment]
I created an upstream issue with sqlfluff: 
https://github.com/sqlfluff/sqlfluff/issues/3892

cc @alanmcruickshank

**Comment by syphar** [comment]
@jose-elias-alvarez fyi, 

setting `ignore_stderr = false` and the fixed `check_exit_code` on the source will lead to the call just failing without inserting the error message into the text. 

Though in this case it feels like the sqlfluff output is something we should handle, because it's some intermediate result.

**Pull request closed without merging**
