### PR TITLE
feat(builtins): add source for htmlbeautifier

### PR DESCRIPTION
**Pull request by johnpitchko**
Adds the [htmlbeautifier](https://github.com/threedaymonk/htmlbeautifier) as a builtin formatting source.

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
LGTM, thanks! Could you just run the source through `stylua`?

**Comment by johnpitchko** [comment]
Sure thing.

**Comment by johnpitchko** [comment]
Ok I think its good now.

**Comment by jose-elias-alvarez** [comment]
Thanks!

**Pull request merged**
