### PR TITLE
feat(diagnostics): fallback_severity option for per built-in

### PR DESCRIPTION
**Pull request by chaneyzorn**
This patch makes `fallback_severity` seem to `diagnostics_format`.

### CODE REVIEW

**Comment by chaneyzorn** [comment]
[trouble.nvim](https://github.com/folke/trouble.nvim) renders diagnostics sorted by diagnostics.severity. The global `fallback_severity` sets to `vim.diagnostic.severity.ERROR`, which makes the unspecified-severity diagnostics range before other explicit-severity diagnostics.

This patch allows user to specified fallback-severity for single built-in diagnostics, such as `cspell`:

image


fallback_severity for per built-in might seem a little strange, but I can't find a easy way to customize the built-in diagnostics severity. 

Such as: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/621 https://github.com/jose-elias-alvarez/null-ls.nvim/issues/538 https://github.com/jose-elias-alvarez/null-ls.nvim/pull/625

Overriding `on_output` is a heavy way.

May we need a `postprocess` (lua/null-ls/diagnostics.lua) hook for user? But It may need more works.

**Comment by jose-elias-alvarez** [comment]
This is a reasonable change, but one reason I'm hesitant to merge it is because the idea of a `fallback_severity` is opaque. Basically, this would only be used if the built-in does not specifically define a severity, but that's not clear without looking at the built-in's source.

I wouldn't be opposed to adding a user hook, since it would effectively solve this and other issues by making it possible to customize anything about the diagnostics. I don't think it should be too hard to add, either–we'd just need to add a new generator option and check for it in `postprocess`.

**Comment by chaneyzorn** [comment]
I think so~

Since this involves the design of the API, I think it's better to leave it to the author to take it over ;D

The PR can be closed at any time, please let me know if I can be of any help.

**Comment by jose-elias-alvarez** [comment]
I added a general `diagnostics_postprocess` hook in 51f336638100ba1462e9c1fb0831464e44d02aef that should handle this and other cases. Thank you for the PR and for your input!

**Pull request closed without merging**
