### PR TITLE
fix diagnostics not reporting if multiple sources on the same file

### LINKED ISSUE #172: Using multiple diagnostics sources on a same filtype seems to only report the last registred
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.5.0

### Steps to reproduce

Add two diagnostics sources for the same filetype (eg. psalm and phpstan for php).

    null_ls.register(null_ls.builtins.diagnostics.phpstan)
    null_ls.register(null_ls.builtins.diagnostics.psalm)

When editing a file, only the last diagnostic source is displayed

### Expected behavior

Both sources should be displayed

### Actual behavior

Only the last registred source is displayed

### Debug log

```
null-ls log: /home/gilles/.cache/nvim/null-ls.log
Detected filetype: php

2 source(s) active for this buffer:

Diagnostics: psalm, phpstan
```

```
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP notification for method textDocument/didChange
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: spawning command ./vendor/bin/phpstan with args:
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: { "analyze", "--error-format", "json", "--no-progress", "/tmp/lua_SJ8fiz.php" }
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: spawning command ./vendor/bin/psalm with args:
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: { "--output-format=json", "--no-progress", "/tmp/lua_oAbIYy.php" }
[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: error output: [{"severity":"error","line_from":38,"line_to":38,"type":"TooFewArguments","message":"Too few arguments for method Mediapa
\\Application\\Offers\\OffersGroupRepository::bysluginstorage saw 1","file_name":"..\/..\/..\/..\/..\/..\/..\/..\/tmp\/lua_oAbIYy.php","file_path":"\/tmp\/lua_oAbIYy.php","snippet":"        $result = $this->bySlugInStorage($slug);","se
bySlugInStorage","from":1026,"to":1041,"snippet_from":1001,"snippet_to":1049,"column_from":26,"column_to":41,"error_level":-1,"shortcode":25,"link":"https:\/\/psalm.dev\/025","taint_trace":null,"other_references":null}]

[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: output: nil
[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: error output: Note: Using configuration file /home/gilles/workspace/new-stack/mediapart/projects/baseadmin/basetunnel/phpstan.neon.

[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: output: {"totals":{"errors":0,"file_errors":1},"files":{"/tmp/lua_SJ8fiz.php":{"errors":1,"messages":[{"message":"Method Mediapart\\Bas
cation\\Offers\\OffersGroupRepository::bySlugInStorage() invoked with 1 parameter, 2 required.","line":38,"ignorable":true}]}},"errors":[]}
[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: received diagnostics from generators
[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: { {
    code = 25,
    col = 26,
    end_col = 41,
    end_row = 38,
    message = "Too few arguments for method Mediapart\\Basetunnel\\Application\\Offers\\OffersGroupRepository::bysluginstorage saw 1",
    range = {
      end = {
        character = 40,
        line = 37
      },
      start = {
        character = 25,
        line = 37
      }
    },
    row = 38,
    severity = 1,
    source = "./vendor/bin/psalm"
  } }
```

### Help

Yes

### Implementation help

_No response_

### PR DESCRIPTION
**Pull request by gbprod**
Fixes #172 #174

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Thank you for putting this in! I want to look into this issue more to see if it’s a regression caused by a recent change (since I imagine we would have already seen reports otherwise) and also to see why copying `params` in the generator loop is not working. In the meantime, I’m glad to have this here as a solution for users who want an immediate fix.

**Comment by mystilleef** [comment]
This fixes the `markdown` issue in #177.

**Comment by bpinto** [comment]
@jose-elias-alvarez if I may, I believe you have said in another issue that you won't have your computer with you until the end of the week? Since more and more people are reporting this issue and this, even if temporary, fix solves it. I think it would be nice to merge and revert later when you have the time to look into it.

**Comment by jose-elias-alvarez** [comment]
@bpinto True - merging this for now seems like a good idea.

**Pull request merged**
