### PR TITLE
feat(luacheck): enable project diagnostics

### PR DESCRIPTION
**Pull request by hungpt2702**
This pull request enables project diagnostics for `luacheck`.

### CODE REVIEW

**Comment by kylo252** [comment]
Is this not supposed to work interactively? because you've effectively removed reading from stdin in this case.

**Comment by jose-elias-alvarez** [comment]
Right, I think this changes the current behavior of the `luacheck` source in a way that's surprising for current users. Maybe this would be best as a separate source, something like `luacheck_project`?

**Comment by hungpt2702** [comment]
@jose-elias-alvarez I could implement it as a separate source. However, I wonder if it is currently possible to make project diagnostics update on change?

**Comment by jose-elias-alvarez** [comment]
Unless a linter supports something like JSON via `stdin`, I don't think it's really possible, since there's no way for the linter to be aware of Neovim buffer state. If you look at your changes, you're telling `luacheck` to check all the files in the root directory, so it necessarily has to check files as they are on disk (not in Neovim). I also suspect it would cause performance issues on larger projects, so it's probably not a good idea in general.

**Pull request closed without merging**
