### PR TITLE
Add yamlfix formatter to built-ins

### PR DESCRIPTION
**Pull request by goetzc**

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
LGTM, could you just run the source file through `stylua` to make CI happy?

**Comment by goetzc** [comment]
Forgot about that, was just running the formatter of lua-ls. Now it's done :)

**Comment by shauryagoel** [comment]
Hi @goetzc, I am getting the following error when opening a yaml file-
 `[null-ls] failed to load builtin yamlfix for method formatting; please check your config`. Have you faced similar issue?

**Comment by goetzc** [comment]
Hi @shauryagoel, I haven't seen that error. I suggest you to open a thread in the [discussion section](https://github.com/jose-elias-alvarez/null-ls.nvim/discussions) and include more [logging information](https://github.com/jose-elias-alvarez/null-ls.nvim#how-do-i-enable-debug-mode-and-get-debug-output).

**Pull request merged**
