### PR TITLE
feat(deno_fmt): respect textwidth and shiftwidth

### PR DESCRIPTION
**Pull request by jceb**

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Seems like a good default, thanks!

**Review by anasrar — COMMENTED** [review]
this make deno ignore format setting on  [configuration file](https://deno.land/manual@v1.29.1/getting_started/configuration_file#configuration-file)

**Comment by jose-elias-alvarez** [comment]
> this make deno ignore format setting on [configuration file](https://deno.land/manual@v1.29.1/getting_started/configuration_file#configuration-file)

So the CLI settings will always override the config file? If so I think we should revert this.

**Comment by jceb** [comment]
> this make deno ignore format setting on [configuration file](https://deno.land/manual@v1.29.1/getting_started/configuration_file#configuration-file)

I'd say if the configuration file has different settings than the editor deno and the will always clash. The way to fix it is to provide the exact same settings to deno and to the editor, e.g. automatically via [editorconfig](https://editorconfig.org/).

**Comment by anasrar** [comment]
why not just check the root project if has `deno.json` or `deno.jsonc`, if not present just use current editor setting otherwise use `deno.json` (the default behavior `deno fmt`)

**Comment by jceb** [comment]
Considering that there are other text editors out there that can't rely on a custom null-ls behavior to detect `deno.json` they'll just rely on editor settings to  format code. This leads me back to ensuring that the editor is configured properly.

**Pull request merged**
