### PR TITLE
fix: resolve root_dir for single files

### PR DESCRIPTION
**Pull request by kylo252**

### CODE REVIEW

**Comment by kylo252** [comment]
@jose-elias-alvarez, I needed to make a small change to handle root_dir for single file mode. Please let me know if it fixes the issue.

**Comment by jose-elias-alvarez** [comment]
I’m away for the weekend and won’t have access to a computer until Monday, so I can’t properly review this. Ideally we could just fix the indexing issue from #378 for now then go over these other changes later. Is that possible?

**Comment by kylo252** [comment]
> I’m away for the weekend and won’t have access to a computer until Monday, so I can’t properly review this. Ideally we could just fix the indexing issue from #378 for now then go over these other changes later. Is that possible?

Was already doing what you wanted, see #382 :)

**Comment by jose-elias-alvarez** [comment]
@kylo252 We can continue working on this if you like. Single-file support seems like a natural fit for null-ls, but I'm not familiar with the advantages / disadvantages.

**Comment by kylo252** [comment]
> @kylo252 We can continue working on this if you like. Single-file support seems like a natural fit for null-ls, but I'm not familiar with the advantages / disadvantages.

It's basically that `lspconfig` has sort of dropped support for using `dirname`, there's even a CI check that will get triggered if you attempt to add it back again 😄 

Other than that, I'm not sure that there's much between them. 

One thing I've been having trouble with currently is that `luacheck` doesn't update its cwd, so it's not reading the current project `.luacheckrc`.  I'm going to test to see if this PR helps, but I'll open a new ticket to track it anyway.

**Comment by jose-elias-alvarez** [comment]
It's very likely that I'll merge #389 soon, which should make this irrelevant. Not sure about the Luacheck `cwd` problem, but feel free to open an issue with a reproduction, since everything related to `root_dir` should work the same way.

**Pull request closed without merging**
