### PR TITLE
add .null-ls-root to LSP root patterns

### PR DESCRIPTION
**Pull request by kabouzeid**
Allows to explicitly set the project root for certain projects

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
This is a good idea, thanks! Could we add a note to the documentation? We don't have an ideal place for it but maybe [CONFIG](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/CONFIG.md) could work.

**Comment by MunifTanjim** [comment]
Instead of hardcoding such a specific filename `.null-ls-root` (which is only ever useful for this plugin), can use a global variable maybe (e.g. `vim.g.null_ls_root_file`)? That way we can set that variable in our config or project local settings (exrc)?

**Comment by jose-elias-alvarez** [comment]
@MunifTanjim Something like this is already possible to do via lspconfig:

```lua
require("lspconfig")["null-ls"].setup({
    root_dir = function(fname)
        return "my-root-dir"
    end,
})
```

Arguably, that also makes this PR unnecessary, though I can still see it as a convenient workaround.

**Comment by kabouzeid** [comment]
There are several language servers that leverage this technique, see eg `.ccls-root` (https://github.com/MaskRay/ccls/wiki/FAQ#project-root-detection).

The problem with
```lua
require("lspconfig")["null-ls"].setup({
    root_dir = function(fname)
        return "my-root-dir"
    end,
})
```
is that it overwrites the original `root_dir` function which I would have to duplicate here.

**Comment by jose-elias-alvarez** [comment]
Yep, I think this could be a simple solution for certain use cases. Thank you for this!

**Pull request merged**
