### PR TITLE
WIP: showcase automatic vimdoc conversion with ts-vimdoc

### PR DESCRIPTION
**Pull request by ibhagwan**
Hi @jose-elias-alvarez,

I'm sure you've heard this before many times, nevertheless, thank you for your wonderful work :-)

Browsing through the issues (to familirize myself better with the plugin and its lesser known options), I noticed this comment from: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/859#issuecomment-1124124737:

> Because it takes a lot of work to write a separate help page + the existing documentation. There's scripts to convert them automatically but I haven't had the time to look into them, and given the structure of our documentation I'm not sure the conversion would produce good results.

Remebering I also had a similar stance against automated conversions (you can read my initial reaction to the idea... https://github.com/ibhagwan/fzf-lua/pull/81) I thought I'd showcase what I was able to achieve with my improved version of what used to be `babelfish.nvim`, now named [`ts-vimdoc`](https://github.com/ibhagwan/ts-vimdoc.nvim).

At the end of the day I didn't see myself maintining a full-on separate vimdoc file (and I don't think you want that either) and the conversion tools are a very decent compromise.

IMHO, the conversion came out quite nice, aside from some very long titles which can be adjusted in the `.md` file I think it's very workable, the file `null-ls.txt` is the conversion of the main `README.md`, the rest of the txt files under `/doc` are self explanatory, all were generated pretty easily by doing this (which can also be turned into github CI action):
```#
git clone https://github.com/jose-elias-alvarez/null-ls.nvim
git clone https://github.com/ibhagwan/ts-vimdoc.nvim
cd null-ls.nvim
../ts-vimdoc.nvim/scripts/docgen.sh README.md ./doc/null-ls.txt null-ls
../ts-vimdoc.nvim/scripts/docgen.sh doc/CONFIG.md doc/CONFIG.txt null-ls
<repeat for all .md files>
```

There's also the much more mature [`panvimdoc`](https://github.com/kdheepak/panvimdoc) by @khdeepak which I highly recommend, test it out and see which output fits your needs better.

If you don't feel this meets the project's goals, I totally understand but I do beleive there's some added value in having the documentation searchable through `:help`.

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Wow, this is great! Thanks for putting in the time to set this up. I agree completely - I think it's super valuable to have the documentation in `:help`, even if it's not 100% perfect. 

I will take a closer look at this over the weekend, see how I can adjust the source files to better account for help file generation, and see if I can set up a CI action, too.

**Comment by ibhagwan** [comment]
Glad you liked it :)

> and see if I can set up a CI action, too.

Lmk if you’re interested and I’ll setup the CI action on this PR’s fork, might save you a few minutes?

**Comment by jose-elias-alvarez** [comment]
> Lmk if you’re interested and I’ll setup the CI action on this PR’s fork, might save you a few minutes?

That would be a huge help, thank you!

**Comment by ibhagwan** [comment]
Added the workflow but couldn't really test it as it won't run on my fork or here, I think it should work, I'm sure you'll figure it out :-)

**Comment by jose-elias-alvarez** [comment]
Alright, I tried this out locally and it's super simple. I don't have a lot of bandwidth to pick this up now, but I think the next step is to tweak our Markdown files so that they work better as Vim help files, either manually or by modifying how we generate them in the first place. I also think some of the files are not necessarily relevant, so I want to see how other sources like ALE handle these cases and think about what users might want to see within Neovim. 

Thanks again for the PR! Once I get more time to work on this, I'll follow up on the ts-vimdoc repo about a couple of minor issues I've seen in the generated documentation / potential features.

**Comment by mskelton** [comment]
I'm taking a stab at forking null-ls given the recent announcement that null-ls is being archived, and I've implemented this in https://github.com/mskelton/null-ls.nvim/commit/62336fcd

One thing I noticed is that it doesn't handle the multiple files very well since it results in a lot of conflicting tag names. I think some of this could be resolved by merging the docs somewhat, but for the sources that will still be a problem.

**Pull request closed without merging**
