### PR TITLE
ci: fix the metadata-update workflow

### PR DESCRIPTION
**Pull request by kylo252**

### CODE REVIEW

**Comment by kylo252** [comment]
@jose-elias-alvarez, so this worked correctly when the branch belonged to the repo, see https://github.com/kylo252/null-ls.nvim/pull/1, so it should at least work for all _your_ PRs 😄 

Let's see how to get this to choose the correct ref, so it can work on any PR.

**Comment by kylo252** [comment]
This still works on my fork. So I think you have some authentication issue going on that you need to figure out. You can also try it yourself from a branch you created to narrow down what's going.

Also, take a look here at this section: See: https://github.com/stefanzweifel/git-auto-commit-action#troubleshooting

**Comment by jose-elias-alvarez** [comment]
So this failed with the same authentication error when I tried it as-is on my own branch, but deleting `ref: ${{ github.head_ref }}` under the `actions/checkout@v2` action seems to fix it. Could you see if that works for you, too?

**Comment by kylo252** [comment]
> So this failed with the same authentication error when I tried it as-is on my own branch, but deleting `ref: ${{ github.head_ref }}` under the `actions/checkout@v2` action seems to fix it. Could you see if that works for you, too?

I added that because otherwise it doesn't know which ref to use, see my first comment, here's the error: https://github.com/jose-elias-alvarez/null-ls.nvim/runs/4523040454?check_suite_focus=true

**Comment by kylo252** [comment]
damn, it worked!

**Comment by kylo252** [comment]
Can I reset the commits to make sure it's still working fine?

**Comment by jose-elias-alvarez** [comment]
stefanzweifel/git-auto-commit-action#117 led me to try using `push`, and stupidly enough it seems to work. I'm seeing some weird issues with actions not showing up, but that may be because I triggered so many in such a short time. Let's try resetting all the test commits and see.

**Comment by kylo252** [comment]
Now it never got triggered. 

I think we're mixing up the ref and the trigger here, so as far I can tell from the commits I saved is that at least one of these combinations should work:


```diff
diff --git a/.github/workflows/docgen.yml b/.github/workflows/docgen.yml
index f1df7178..64be0906 100644
--- a/.github/workflows/docgen.yml
+++ b/.github/workflows/docgen.yml
@@ -10,7 +10,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
         with:
-          ref: ${{ github.head_ref }}
+          ref: ${{ github.event.pull_request.head.sha }}
 
       - uses: rhysd/action-setup-vim@v1
         with:
```

or 

```diff
diff --git a/.github/workflows/docgen.yml b/.github/workflows/docgen.yml
index 16d7f0cd..fd952915 100644
--- a/.github/workflows/docgen.yml
+++ b/.github/workflows/docgen.yml
@@ -1,6 +1,6 @@
 name: docgen
 
-on: pull_request
+on: ["push", "pull"]
 
 jobs:
   metadata-diff:
@@ -10,7 +10,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
         with:
-          ref: "refs/pull/${{ github.event.number }}/merge"
+          ref: ${{ github.head_ref }}
 
       - uses: rhysd/action-setup-vim@v1
         with:
```

**Comment by jose-elias-alvarez** [comment]
Feel free to play around with it more, I won't have any more time today. The good thing is that once we get the ref issue solved, everything is working great.

**Comment by kylo252** [comment]
> Feel free to play around with it more, I won't have any more time today. The good thing is that once we get the ref issue solved, everything is working great.

I got scared it won't work with this, but looks like it's fine 😃 

Do you want me to squash all the commits, or what's the plan?

**Comment by jose-elias-alvarez** [comment]
Great! I'll review and test this in a couple of days. For now let's squash the commits to test out different configs but keep the loop refactor separate.

**Comment by jose-elias-alvarez** [comment]
Seems to work, let's give it a shot!

**Pull request merged**
