### PR TITLE
fix(lspconfig): update the setup workflow

### LINKED ISSUE #378: Cannot use null-ls with the latest `neovim/nvim-lspconfig`
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

  NVIM v0.6.0-dev+634-geb876a0a6 

### null-ls config

```lua
null_ls.config {
	debug = true,
	sources = {...}
}
lspconfig["null-ls"].setup { ... }
```

### Steps to reproduce

Run require('lspconfig')['null-ls'].setup {...}

### Debug log

```
Cannot access configuration for null-ls. Ensure this server is listed in `server_configurations.md` or added as a custom server.
packer.nvim: Error running config for null-ls.nvim: ...pack/packer/start/null-ls.nvim/lua/null-ls/lspconfig.lua:100: attempt to index field 'manager' (a nil value)
```

### Help

No

### Implementation help

_No response_

### PR DESCRIPTION
**Pull request by kylo252**
Update to match the latest changes in `lspconfig` that were introduced in https://github.com/neovim/nvim-lspconfig/pull/1479

Fixes #378

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Thank you!!

**Comment by jose-elias-alvarez** [comment]
One question: will `workspaceFolders[1]` always be defined? It seems like a good idea to guard against the case that it’s not (or to make the change later if it’s not strictly necessary for the immediate issue).

**Comment by numToStr** [comment]
Now, I am not able to save the buffer, getting the error `E13: File exists (add ! to override)`. Then doing `w!` I got the following error

```
Error detected while processing CursorHold Autocommands for "*":
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:
155: Vim(lua):E5108: Error executing lua ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:57: attempt to index field 'cmd' (a nil value)
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
```

**Comment by jose-elias-alvarez** [comment]
Right, I think this might require more work to figure out. We may be able to take care of the specific RPC issue for now by reverting the changes from 4e9e786e7621dcbe0c3d8d473fc434a2a2d2687b.

**Comment by numToStr** [comment]
@jose-elias-alvarez yes, we should only focus on fixing the compat issue with lspconfig.

**Comment by kylo252** [comment]
> Now, I am not able to save the buffer, getting the error `E13: File exists (add ! to override)`. Then doing `w!` I got the following error
> 
> ```
> Error detected while processing CursorHold Autocommands for "*":
> E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:
> 155: Vim(lua):E5108: Error executing lua ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:57: attempt to index field 'cmd' (a nil value)
> stack traceback:
>         [C]: in function 'cmd'
>         ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>
>         [string ":lua"]:1: in main chunk
> ```

The issue is fixed in #381.

**Pull request merged**
