### PR TITLE
Add faq for timeout error message to FAQ section in README.md

### PR DESCRIPTION
**Pull request by iDuuck**
Having this problem my self, and seeing this message pop up in the issues (#572) of this project, I decided to create this little FAQ in the FAQs section.

Problem here: In my case, `rubocop` took longer than the default timeout, so I decided to drop the formatting for rubocop, since it takes to long. Other solution would be to just increase the timeout for any `formatting_sync` call, however this slowed down my editor performance massively, so I just dropped formatting support.

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Thanks! I agree that adding a snippet explicitly showing how to increase the timeout is a good idea.

**Comment by iDuuck** [comment]
Will add this asap, thanks for the reviews.

**Comment by iDuuck** [comment]
Updated!

**Comment by jose-elias-alvarez** [comment]
Thank you!

**Pull request merged**
