### PR TITLE
feat: add PMD as a builtin

### LINKED ISSUE #1194: Add pmd as a built-in
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Add [pmd](https://pmd.github.io) as a built-in diagnostics tool.

I already have a rough version working in my own configs.

### Help

Yes

### Implementation help

PMD requires a config file/ruleset to be specified. It ships some configs in its JAR file, which can be loaded by specifying a classpath resolvable file in the JAR. Though likely users would want to specify different configs per project.

So what I would need help with is how I can read a vim variable (read from a local vimrc for example) and use that to compose the arguments for the executable on each run.

Finally, some performance tweaks might also be nice, since I did some involuntary performance tests as commented on #596.

### PR DESCRIPTION
**Pull request by kmoschcau**
Closes #1194

### CODE REVIEW

**Review by jose-elias-alvarez — COMMENTED** [review]
This also looks good, though I'd make the same changes to documentation that I recommended on your other PR. Thanks!

**Comment by jose-elias-alvarez** [comment]
Looks like this needs a rebase since I merged your other PR, but once that's set I think this is good to go.

**Comment by kmoschcau** [comment]
I fixed the merge conflict.

**Comment by jose-elias-alvarez** [comment]
Thanks!

**Pull request merged**
