### PR TITLE
Add buildifier to formatting built-ins

### PR DESCRIPTION
**Pull request by kgreenek**
Closes https://github.com/jose-elias-alvarez/null-ls.nvim/issues/496

### CODE REVIEW

**Comment by kgreenek** [comment]
Tested by updating my dotfiles to use this fork:
https://github.com/kgreenek/dotfiles/blob/master/nvim/lua/kgreenek/lsp/null_ls.lua#L9

**Comment by jose-elias-alvarez** [comment]
Could you also update the documentation? Other than that this LGTM.

**Comment by kgreenek** [comment]
PTAL

Added buildifier to docs.

**Comment by jose-elias-alvarez** [comment]
Great, thanks!

**Pull request merged**
