### PR TITLE
feature(yapf): allow range_format

### PR DESCRIPTION
**Pull request by meijieru**
Enable range formatting for yapf & black

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Are you sure this works? I think this will make range formatting format the entire document, since the arguments aren't getting modified. I recommend taking a look at the [implementation for Prettier](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/prettier.lua) and see if we can do something similar for these formatters.

**Comment by meijieru** [comment]
I hacked it and use it for several days.
Just find that they always format the entire file.
Sorry for that, and I will look at it later this week.

**Comment by meijieru** [comment]
I fix the implementation for `yapf` and update the documentation.

There are some limitations though:
1. It is line-based.
2. Even range is given, it may change the out-of-range content like whitespace, which comes from the plugin itself.

**Comment by meijieru** [comment]
For `black` we should wait for https://github.com/psf/black/issues/830

**Comment by jose-elias-alvarez** [comment]
LGTM, thanks!

**Pull request merged**
